from __future__ import annotations

SQL_INJECTION_PATTERNS: list[tuple[str, str]] = [
    ("sql_concat_select", r"SELECT\s+.*\+"),
    ("sql_concat_insert", r"INSERT\s+INTO\s+.*\+"),
    ("sql_concat_update", r"UPDATE\s+.*\+"),
    ("sql_concat_delete", r"DELETE\s+FROM\s+.*\+"),
    ("sql_concat_where", r"WHERE\s+.*\+"),
    ("sql_concat_limit", r"LIMIT\s+.*\+"),
    ("sql_fstring", r"f\".*SELECT.*\{.*\}"),
    ("sql_format", r"\.format\(.*SELECT"),
    ("sql_percent", r"%s"),
    ("sql_raw_query", r"execute\(.+\+"),
    ("sql_raw_cursor", r"cursor\.execute\(.+\+"),
    ("sql_raw_statement", r"statement\.execute\(.+\+"),
    ("sql_raw_query_string", r"query\s*=\s*\".*\+"),
    ("sql_raw_query_single", r"query\s*=\s*'.*\+"),
    ("sql_raw_query_backtick", r"query\s*=\s*`.*\+"),
    ("sql_concat_input", r"\+\s*request\."),
    ("sql_concat_params", r"\+\s*params\["),
    ("sql_concat_req_body", r"\+\s*body\["),
    ("sql_concat_querystring", r"\+\s*query\["),
    ("sql_concat_user_input", r"\+\s*user\w*"),
    ("sql_concat_id", r"\+\s*id\b"),
    ("sql_concat_name", r"\+\s*name\b"),
    ("sql_concat_email", r"\+\s*email\b"),
    ("sql_interpolated", r"\$\{.*\}.*SELECT"),
    ("sql_template_literal", r"`.*SELECT.*\$\{"),
    ("sql_concat_concat", r"\.concat\(.*SELECT"),
    ("sql_string_builder", r"StringBuilder\s*\(\)"),
    ("sql_append", r"append\(\".*SELECT"),
    ("sql_execute_query", r"executeQuery\(.*\+"),
    ("sql_execute_update", r"executeUpdate\(.*\+"),
    ("sql_execute_raw", r"ExecuteSqlRaw\(.*\+"),
    ("sql_execute_scalar", r"ExecuteScalar\(.*\+"),
    ("sql_query_raw", r"FromSqlRaw\(.*\+"),
    ("sql_interpolated_param", r"interpolated.*SELECT"),
]
