from __future__ import annotations

XSS_PATTERNS: list[tuple[str, str]] = [
    ("xss_inner_html", r"innerHTML\s*=\s*"),
    ("xss_outer_html", r"outerHTML\s*=\s*"),
    ("xss_document_write", r"document\.write\("),
    ("xss_document_writeln", r"document\.writeln\("),
    ("xss_eval", r"\beval\("),
    ("xss_set_timeout", r"setTimeout\(\s*\""),
    ("xss_set_interval", r"setInterval\(\s*\""),
    ("xss_jquery_html", r"\$\([^)]*\)\.html\("),
    ("xss_jquery_append", r"\$\([^)]*\)\.append\("),
    ("xss_jquery_prepend", r"\$\([^)]*\)\.prepend\("),
    ("xss_jquery_before", r"\$\([^)]*\)\.before\("),
    ("xss_jquery_after", r"\$\([^)]*\)\.after\("),
    ("xss_dom_parser", r"DOMParser\("),
    ("xss_create_contextual_fragment", r"createContextualFragment\("),
    ("xss_set_attribute", r"setAttribute\(\s*['\"]on"),
    ("xss_event_handler_attr", r"on\w+\s*=\s*['\"]"),
    ("xss_template_literal", r"`.*<script"),
    ("xss_string_concat", r"\+\s*['\"].*<"),
    ("xss_v_html", r"v-html\s*=\s*"),
    ("xss_dangerously_set", r"dangerouslySetInnerHTML"),
    ("xss_ng_bind_html", r"ng-bind-html"),
    ("xss_mark_safe", r"mark_safe\("),
    ("xss_raw_html", r"\|safe\b"),
    ("xss_unescaped", r"{{{.*}}}"),
    ("xss_twig_raw", r"\|raw\b"),
    ("xss_ejs_unescaped", r"<%-"),
    ("xss_handlebars_unescaped", r"{{{"),
    ("xss_sprintf_html", r"sprintf\(.*<"),
    ("xss_render_unsafe", r"render\(.*<"),
    ("xss_html_safe", r"html_safe"),
    ("xss_safe_buffer", r"SafeBuffer"),
    ("xss_script_tag", r"<script"),
    ("xss_inline_svg", r"<svg"),
    ("xss_onerror", r"onerror\s*="),
    ("xss_onload", r"onload\s*="),
]
