"""
This module provides the `CrossFileResolver`, a utility for analyzing and summarizing
the dependency relationships between different modules in the project.

After the `ImportProcessor` has collected all the import mappings, this resolver
can be used to build an index of which modules depend on which other modules. It
is primarily used for generating statistics and logging a summary of the project's
dependency structure, such as identifying the most imported or most depended-on modules.
"""

from __future__ import annotations

from dataclasses import dataclass

from loguru import logger


@dataclass
class CrossFileStats:
    """
    A data class to hold statistics about cross-file dependencies.

    Attributes:
        total_modules (int): The total number of modules that were analyzed.
        total_edges (int): The total number of dependency edges (imports) found between modules.
        top_imports (list[tuple[str, int]]): A list of the top modules that import the most other modules.
        top_dependents (list[tuple[str, int]]): A list of the top modules that are most depended on by others.
    """

    total_modules: int
    total_edges: int
    top_imports: list[tuple[str, int]]
    top_dependents: list[tuple[str, int]]


class CrossFileResolver:
    """
    Analyzes dependencies between files based on the collected import mappings.

    This class takes the `import_mapping` generated by the `ImportProcessor` and
    builds a dependency graph in memory to calculate and log statistics about the
    project's structure.
    """

    def __init__(self, import_mapping: dict[str, dict[str, str]]) -> None:
        """
        Initializes the CrossFileResolver.

        Args:
            import_mapping (dict[str, dict[str, str]]): A dictionary mapping module qualified
                names to their import data, as produced by the `ImportProcessor`.
        """
        self.import_mapping = import_mapping

    def build_index(self) -> CrossFileStats:
        """
        Builds an index of cross-file dependencies and calculates key statistics.

        It constructs both a forward dependency graph (module -> its imports) and a
        reverse dependency graph (module -> its dependents) to compute the metrics.

        Returns:
            A `CrossFileStats` object containing the calculated statistics.
        """
        dependencies: dict[str, set[str]] = {}
        reverse_deps: dict[str, set[str]] = {}

        for module, imports in self.import_mapping.items():
            for _, target in imports.items():
                dependencies.setdefault(module, set()).add(target)
                reverse_deps.setdefault(target, set()).add(module)

        total_edges = sum(len(targets) for targets in dependencies.values())
        total_modules = len(self.import_mapping)

        top_imports = sorted(
            ((module, len(targets)) for module, targets in dependencies.items()),
            key=lambda item: item[1],
            reverse=True,
        )[:10]

        top_dependents = sorted(
            ((module, len(sources)) for module, sources in reverse_deps.items()),
            key=lambda item: item[1],
            reverse=True,
        )[:10]

        return CrossFileStats(
            total_modules=total_modules,
            total_edges=total_edges,
            top_imports=top_imports,
            top_dependents=top_dependents,
        )

    def log_summary(self) -> None:
        """
        Calculates and logs a summary of the cross-file dependency statistics.

        This method provides a high-level overview of the project's dependency
        structure, including the total number of modules and edges, and highlights
        the most interconnected parts of the codebase.
        """
        stats = self.build_index()
        logger.info(
            "Cross-file resolver: modules={}, edges={}",
            stats.total_modules,
            stats.total_edges,
        )
        if stats.top_imports:
            logger.info("Top importers: {}", stats.top_imports)
        if stats.top_dependents:
            logger.info("Top dependents: {}", stats.top_dependents)
